openapi: "3.0.1"
info:
  title: "Ecommerce API Gateway"
  version: "1.0"
paths:
  /products:
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        uri: "http://products_service:3000/products"
        passthroughBehavior: "when_no_match"
        httpMethod: "ANY"
        type: "http_proxy"
        
  /products/{proxy+}:
    x-amazon-apigateway-any-method:
      parameters:
        - name: "proxy"
          in: "path"
          required: true
          schema:
            type: "string"
      x-amazon-apigateway-integration:
        uri: "http://products_service:3000/products/{proxy}"
        passthroughBehavior: "when_no_match"
        httpMethod: "ANY"
        type: "http_proxy"
        requestParameters:
          "integration.request.path.proxy": "method.request.path.proxy"
          
  /orders:
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        uri: "http://orders_service:3000/orders"
        passthroughBehavior: "when_no_match"
        httpMethod: "ANY"
        type: "http_proxy"

  /orders/{proxy+}:
    x-amazon-apigateway-any-method:
      parameters:
        - name: "proxy"
          in: "path"
          required: true
          schema:
            type: "string"
      x-amazon-apigateway-integration:
        uri: "http://orders_service:3000/orders/{proxy}"
        passthroughBehavior: "when_no_match"
        httpMethod: "ANY"
        type: "http_proxy"
        requestParameters:
          "integration.request.path.proxy": "method.request.path.proxy"
